matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libxext-dev
            - libxss-dev
            - libxkbfile-dev
            - rpm
    - os: osx
      if: branch IN (nightly, release)
      osx_image: xcode11

language: node_js
git:
  submodules: false
branches:
  only:
    - develop
    - release
    - nightly
cache: npm

before_install:
  - git submodule update --init --recursive
install:
  - travis_retry npx lerna bootstrap
  - travis_retry npm install node-sass -g
before_script:
  - npm run lint && npm run test
script:
  - |
    if [ $TRAVIS_BRANCH == "release" ]; then
      travis_retry travis_wait 100 npm run build 
    fi
  - |
    if [ $TRAVIS_BRANCH == "nightly" ]; then
      npm version prerelease --preid=nightly -m "%s [skip ci]"
      travis_retry travis_wait 100 npm run build -- --publish always -c.publish.provider=github -c.publish.owner=getferdi -c.publish.repo=nightlies
      if [ $TRAVIS_OS_NAME == "osx" ]; then
        git remote add nightly https://${GH_TOKEN}@github.com/getferdi/ferdi.git > /dev/null 2>&1
        git push --quiet --set-upstream nightly HEAD:nightly >/dev/null 2>&1
      fi
    fi
