version: build-{build}
branches:
  only:
    - develop
    - nightly
    - release
skip_tags: true
skip_branch_with_pr: true

cache:
  - '%APPDATA%\npm-cache'
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.electron-builder'

image: Visual Studio 2019

environment:
  nodejs_version: "14.16.1"

install:
  - appveyor-retry git submodule update --init --recursive
  - ps: Update-NodeJsInstallation $env:nodejs_version
  - cmd: set NODE_OPTIONS=--max-old-space-size=2048
  - cd recipes && npm install && npm run package && cd ..
  - appveyor-retry npx lerna bootstrap

before_build:
  - npm run lint && npm test
  - cmd: set NODE_ENV=production

build_script:
  - appveyor-retry npm run build

for:
-
  branches:
    only:
      - develop
  build_script:
    - appveyor-retry npm run build
-
  branches:
    only:
      - nightly
  only_commits:
    message: /trigger AppVeyor nightly build/
  build_script:
    - appveyor-retry npm run build -- --publish always -c.publish.provider=github -c.publish.owner=getferdi -c.publish.repo=nightlies
-
  branches:
    only:
      - release
  build_script:
    - appveyor-retry npm run build -- --publish always -c.publish.provider=github -c.publish.owner=getferdi -c.publish.repo=ferdi
