# blank_issues_enabled: false
contact_links:
  - name: Ferdi Community Support
    url: https://getferdi.com/faq/
    about: Please see some basic questions here. If your question is not answered, please continue with raising an issue in github.
